### ISSUE TITLE
Money issue

### ISSUE THREAD

**Issue by haeiven** [SoulsCode37/TradeSystem#2]
Hello,

While trading 1M of money but you only have 500k or under 1M, the trade is successful but the other guy don't receive the money. it should cancel the trade instead of saying sucessful.

Best regards,

**Comment by SoulsCode37** [comment]
Hello, since there isn't a specific plugin dependency, but only a command to execute when the trade is finished, i have no way to check if the amount of money selected is valid. I am sorry for this problem, but currently there is no way i could 'fix' this.

**Comment by haeiven** [comment]
You should use vault for transactions, and wait for the vault response to conclude the trade. That's a better way to handle payements I think.

**Comment by SoulsCode37** [comment]
Not every server uses Vault, but i think i could add an option to use Vault as dependency if needed

**Comment by haeiven** [comment]
Mh, Vault is used by all plugins for permissions & money transactions. well, at least 95% of spigot plugins.

**Comment by SoulsCode37** [comment]
Oh didn't knew that, i will add Vault compability in the next update, thanks for the advices
