### ISSUE TITLE
Users still registered with name when disconnecting

### ISSUE THREAD

**Issue by haeiven** [SoulsCode37/TradeSystem#3]
Hello,

Trade System still register users with their username instead of UUID while disconnecting.

Suggested:
- Register an user in the userlist only when he try to use /trade or /tblacklist for the first time.
- Register the UUID & the name (but the name should be updated if the user change his name on mojang)
- When using /tblacklist on a player who doesn't exist in the user list, add a message "this user never user /trade before. You can't block him."

**Comment by SoulsCode37** [comment]
Features/Fixes will be in the next update!
